CREATE PROCEDURE [dbo].[WriteEvent]
	@EventEntry EventEntry READONLY
AS
	INSERT INTO [dbo].[Event](
		 [EventId]			
		,[FormattedMessage]	
		,[Payload]			
		,[ProviderId]		
		,[Timestamp]			
		,[ActivityId]		
		,[RelatedActivityId]	
		,[ProcessId]			
		,[ThreadId]			
		,[Level]				
		,[Opcode]			
		,[Task]				
		,[Version]			
		,[Keywords]			
		,[EventName]			
		,[ProviderName]		
		,[OpcodeName]		
		,[TaskName]			
		,[KeywordsDescription]
	)
	SELECT
		 [EventId]			
		,[FormattedMessage]	
		,[Payload]			
		,[ProviderId]		
		,[Timestamp]			
		,[ActivityId]		
		,[RelatedActivityId]	
		,[ProcessId]			
		,[ThreadId]			
		,[Level]				
		,[Opcode]			
		,[Task]				
		,[Version]			
		,[Keywords]			
		,[EventName]			
		,[ProviderName]		
		,[OpcodeName]		
		,[TaskName]			
		,[KeywordsDescription]
	 FROM @EventEntry